### ISSUE TITLE
Project: Support W3C Verifiable Credentials on Solid

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/cryptography-and-security#5]
@kezike's excellent exploration / prototype of [Verifiable Credentials on Solid](https://github.com/kezike/solid-vc) demonstrated initial implementation feasibility. Now that the [Verifiable Credential Model](https://www.w3.org/TR/vc-data-model/) is an official W3C standard, this is a placeholder issue to track use cases, interoperability and infrastructure requirements for VC use for the Solid ecosystem.

Pre-requisite infrastructure for VCs on Solid:

* [ ] - [#3 - Support for Linked Data Signature key format for WebID Profile docs](https://github.com/solid/cryptography-and-security/issues/3)
* [ ] - [#4 - Key Management API / best practices for Solid pods](https://github.com/solid/cryptography-and-security/issues/4)
* [ ] - (optional but helpful for wider interop) [identity-panel/#1 - Support for Decentralized Identifiers (DIDs)](https://github.com/solid/identity-panel/issues/1)
* [ ] - (optional but helpful) [specification/#101 - WebID Profiles for Groups/Organizations](https://github.com/solid/specification/issues/101) (useful for Issuer applications)

**Comment by kjetilk** [comment]
I see this all over as one of the key use cases.
