### ISSUE TITLE
Project: Client-side encryption for Solid pods

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/cryptography-and-security#6]
Standardization activity on how to do client-side data encryption for personal data storage is heating up in the wider standards community, led by the W3C Credentials Community group and the [Decentralized Identify Foundation (DIF)](https://identity.foundation/) (including Microsoft, Workday, Consensys, and others). This is also relevant to Solid, for use cases that have strong client-side data encryption requirements (such as storage of health records and other high-value items).

The current Linked-Data-friendly standard being incubated jointly by those groups is the [Encrypted Data Vault](https://digitalbazaar.github.io/encrypted-data-vaults/) spec (see the introductory [Encrypted Data Vault requirements paper](https://github.com/WebOfTrustInfo/rwot9-prague/blob/master/draft-documents/encrypted-data-vaults.md)).

This is a placeholder issue to track pre-requisite specs and infrastructure to enable client-side encryption on Solid.

Pre-requisite infrastructure:
* [ ] - [#3 - Support for Linked Data Signature key format for WebID Profile docs](https://github.com/solid/cryptography-and-security/issues/3)
* [ ] - [#4 - Key Management API / best practices for Solid pods](https://github.com/solid/cryptography-and-security/issues/4)
* [ ] - (optional but helpful for wider interop) [identity-panel/#1 - Support for Decentralized Identifiers (DIDs)](https://github.com/solid/identity-panel/issues/1)
